imports:
    - { resource: "@SyliusPayPalPlugin/config/config.yaml" }

sylius_paypal:
    sandbox: false        # ← switch to production facilitator
    enable_express_checkout: false
    logging:
        increased: false
